### PR TITLE
Add bullet changing option

### PR DESCRIPTION
**Pull request by SerVB**
This will allow changing markers:

```kotlin
itemize {
    -"Default marker"
    "--" - "Dash"
    "$-$" - "Dash"
    "$\\ast$" - "Asterisk"
}
```

```
    \begin{itemize}
      \item Default marker
      \item[--] Dash
      \item[$-$] Dash
      \item[$\ast$] Asterisk
    \end{itemize}
```

image

### CODE REVIEW

**Comment by khud** [comment]
I'd like to suggest some useful syntactic sugar for the most common cases:
```kotlin
itemize {
    - "Default marker"
    -- "Dash"
    + "Asterisk" // it would be great to override + anyway
}
```

**Comment by SerVB** [comment]
Done for asterisk.

Can't figure out how to implement `--`. For decrement, I've tried this and similar; can't be compiled:

```kotlin
class Itemize : AbstractListTag("itemize") {
    operator fun String.minus(lhs: String) {
        children.add(TextElement("\\item[$this] $lhs"))
    }

    operator fun String.dec() {  // error: bad method declaration
        children.add(TextElement("\\item[--] $this"))
    }
}
```

Anyway, looking to Int seems like we can't use the decrement anyway because variable is needed and simple string value won't work:
image

I also tried to make double unary minus. I've done this:

```kotlin
data class Item(val content: String)

open class AbstractListTag(name: String) : Environment(name) {
    operator fun String.unaryMinus(): Item {
        val content = this.trimIndent()
        children.add(TextElement("\\item $content"))
        return Item(content)
    }
}

class Itemize : AbstractListTag("itemize") {
    operator fun String.minus(lhs: String) {
        children.add(TextElement("\\item[$this] $lhs"))
    }

    operator fun Item.unaryMinus() {
        children.removeLast()
        children.add(TextElement("\\item[--] $content"))
    }
}
```

And it works only like this: `-(-"Dash")`. For `-- "Dash"`, the compiler searches for decrement and doesn't find it of course.

Do you have an idea how to implement double minus?

Need to mention that we can easily use `.not()` or binary `!` for dash, so if you think it's OK, I'll commit it.

**Comment by khud** [comment]
try `fun String.dec(): String`, I believe the method must return modified value

**Comment by SerVB** [comment]
Tried that (returning `this` and `""`) 🙂 The errors are the same:

image

image

**Comment by khud** [comment]
Looks like a bug. Because it works (can't be defined and used somehow) if I define it on the top level. But you are right, it's complicated. --"xxx" will not work anyway. Let's try to change stuff a bit: - for a dash, ! for the default bullet. What do you think?

**Comment by SerVB** [comment]
@khud, I think if we are changing stuff, let's do it like this:

operator | before this PR | currently in the PR | your proposal | my proposal
---|---|---|---|---
`-` | `\item` | `\item` | `\item[--]` | `\item[--]`
`+` | append raw text | `\item[$\ast$]` | `\item[$\ast$]` | `\item`
`!` | N/A | N/A | `\item` | `\item[$\ast$]`

I just think `+` is more natural to use for default marker...

**Comment by SerVB** [comment]
Let me close it because no more work is planned here in the near future, but the PR is shown as pending in my UI

**Pull request closed without merging**
